menu:
  Archives: /archives
  Projects: /projects
  About: /about
  GitHub: https://github.com/stanzhai

widgets: 
- search
- category
- tagcloud
- recent_posts
- twitter

excerpt_link: 阅读全文


addthis:
  enable: true

fancybox: true

google_analytics:
rss:
